[package]
name = "beethoven-deposit-jupiter"
description = "Jupiter Earn deposit implementation for Beethoven"
version = "0.0.1"
license = "MIT"
edition = "2021"

[dependencies]
beethoven-core = { path = "../../core" }
pinocchio = { version = "0.10.0", features = ["cpi"] }
